@baseUrl = http://localhost:5001/api/v1

### Login Request
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "thanhtung95@gmail.com",
  "password": "kh123456"
}

### Luu token vao bien
@authToken = {{loginRequest.response.body.$.data.token}}

### Get User Profile
# @name getUserProfile
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}