@baseUrl = http://localhost:5001/api/v1

### Login Request
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@vnrailway.vn",
  "password": "admin123"
}

### Luu token vao bien
@authToken = {{loginRequest.response.body.$.data.token}}

### Get Staff Profile
# @name getStaffProfile
GET {{baseUrl}}/staff/me
Authorization: Bearer {{authToken}}

### Get all users
# @name getAllUsers
GET {{baseUrl}}/users/all
Authorization: Bearer {{authToken}}

### Get all staff
# @name getAllStaff
GET {{baseUrl}}/staff/all
Authorization: Bearer {{authToken}}