USE VNRAILWAY;
GO

CREATE OR ALTER PROCEDURE sp_ApDungUuDai
    @MaUuDai VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SET TRANSACTION ISOLATION LEVEL REPEATABLE READ; 

    BEGIN TRANSACTION;

    -- Lần đọc 1
    SELECT PhanTram 
    FROM UU_DAI_GIA 
    WHERE MaUuDai = @MaUuDai;

    -- Delay 10s 
    WAITFOR DELAY '00:00:10'; 

    -- Lần đọc 2
    SELECT PhanTram 
    FROM UU_DAI_GIA 
    WHERE MaUuDai = @MaUuDai;

    COMMIT TRANSACTION;
END;
GO