USE master
GO
IF DB_ID(N'VNRAILWAY') IS NOT NULL
BEGIN
    ALTER DATABASE VNRAILWAY SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE VNRAILWAY;
END;
GO
CREATE DATABASE VNRAILWAY;
GO
USE VNRAILWAY;
GO

-- ================================================================
-- CẤP ĐỘ 1: CÁC BẢNG DANH MỤC & CẤU HÌNH (Không có FK)
-- ================================================================

-- 1. Bảng THAM_SO
CREATE TABLE THAM_SO (
    MaThamSo VARCHAR(10) NOT NULL,
    TenThamSo NVARCHAR(100),
    GiaTriSo FLOAT,
    GiaTriChuoi NVARCHAR(255),
    NgayHieuLuc DATETIME,
    NgayHetHieuLuc DATETIME,
    MoTa NVARCHAR(255),
    CONSTRAINT PK_THAM_SO PRIMARY KEY (MaThamSo)
);

-- 2. Bảng GA_TAU
CREATE TABLE GA_TAU (
    MaGaTau VARCHAR(10) NOT NULL,
    TenGa NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_GA_TAU PRIMARY KEY (MaGaTau)
);

-- 3. Bảng UU_DAI_GIA
CREATE TABLE UU_DAI_GIA (
    MaUuDai VARCHAR(10) NOT NULL,
    LoaiUuDai NVARCHAR(50),
    MoTa NVARCHAR(255),
    DoiTuong NVARCHAR(50),
    PhanTram INT,
    NgayBatDau DATETIME,
    NgayKetThuc DATETIME,
    TrangThai NVARCHAR(20),
    CONSTRAINT PK_UU_DAI_GIA PRIMARY KEY (MaUuDai),
    CONSTRAINT CK_UU_DAI_GIA_PhanTram CHECK (PhanTram >= 0 AND PhanTram <= 100),
    CONSTRAINT CK_UU_DAI_GIA_ThoiGian CHECK (NgayKetThuc IS NULL OR NgayBatDau <= NgayKetThuc),
    CONSTRAINT CK_UU_DAI_GIA_TrangThai CHECK (TrangThai IN (N'Đang áp dụng', N'Hết hạn', N'Tạm ngưng'))
);

-- 4. Bảng TUYEN_TAU
CREATE TABLE TUYEN_TAU (
    MaTuyenTau VARCHAR(10) NOT NULL,
    TenTuyen NVARCHAR(50),
    KhoangCach FLOAT,
    CONSTRAINT PK_TUYEN_TAU PRIMARY KEY (MaTuyenTau)
);

-- 5. Bảng DOAN_TAU
CREATE TABLE DOAN_TAU (
    MaDoanTau VARCHAR(10) NOT NULL,
    TenTau NVARCHAR(100) NOT NULL,
    HangSanXuat NVARCHAR(100),
    NgayVanHanh DATE NOT NULL,
    LoaiTau NVARCHAR(20) NOT NULL,
    TrangThai NVARCHAR(20),
    CONSTRAINT PK_DOAN_TAU PRIMARY KEY (MaDoanTau),
    CONSTRAINT CK_DOAN_TAU_LoaiTau CHECK (LoaiTau IN (N'Hạng sang', N'Bình thường')),
    CONSTRAINT CK_DOAN_TAU_TrangThai CHECK (TrangThai IN (N'Hoạt động', N'Bảo trì'))
);

-- 6. Bảng KHACH_HANG
CREATE TABLE KHACH_HANG (
    MaKhachHang VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(50) NOT NULL,
    CCCD VARCHAR(12) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL,
    SoDienThoai VARCHAR(10) NOT NULL,
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MaKhachHang),
    CONSTRAINT UQ_KHACH_HANG_CCCD UNIQUE (CCCD),
    CONSTRAINT CK_KHACH_HANG_GioiTinh CHECK (GioiTinh IN (N'Nam', N'Nữ'))
);

-- 7. Bảng NHAN_VIEN (Tự tham chiếu)
CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    CCCD VARCHAR(12) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR(10),
    DiaChi NVARCHAR(255),
    SoDienThoai VARCHAR(10),
    LoaiNhanVien NVARCHAR(20) NOT NULL,
    NVQuanLy VARCHAR(10),
    CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MaNV),
    CONSTRAINT UQ_NHAN_VIEN_CCCD UNIQUE (CCCD),
    CONSTRAINT CK_NHAN_VIEN_NgaySinh CHECK (NgaySinh < GETDATE()),
    CONSTRAINT CK_NHAN_VIEN_GioiTinh CHECK (GioiTinh IN (N'Nam', N'Nữ')),
    CONSTRAINT CK_NHAN_VIEN_LoaiNhanVien CHECK (LoaiNhanVien IN (N'Quản lý', N'Bán vé', N'Lái tàu', N'Toa tàu', N'Quản trị')),
    CONSTRAINT CK_NHAN_VIEN_TuQuanLy CHECK (MaNV <> NVQuanLy),
    CONSTRAINT FK_NHAN_VIEN_QuanLy FOREIGN KEY (NVQuanLy) REFERENCES NHAN_VIEN(MaNV)
);

-- ================================================================
-- CẤP ĐỘ 2: CÁC BẢNG GIÁ (Không có FK)
-- ================================================================

-- 8. Bảng GIA_THEO_LOAI_TAU
CREATE TABLE GIA_THEO_LOAI_TAU (
    MaGiaTau VARCHAR(10) NOT NULL,
    LoaiTau NVARCHAR(20) NOT NULL,
    GiaTien DECIMAL(18, 0),
    CONSTRAINT PK_GIA_THEO_LOAI_TAU PRIMARY KEY (MaGiaTau),
    CONSTRAINT CK_GIA_THEO_LOAI_TAU_Loai CHECK (LoaiTau IN (N'Hạng sang', N'Bình thường')),
    CONSTRAINT CK_GIA_THEO_LOAI_TAU_Gia CHECK (GiaTien >= 0)
);

-- 9. Bảng GIA_THEO_LOAI_TOA
CREATE TABLE GIA_THEO_LOAI_TOA (
    MaGiaToa VARCHAR(10) NOT NULL,
    LoaiToa NVARCHAR(20) NOT NULL,
    GiaTien DECIMAL(18, 0),
    CONSTRAINT PK_GIA_THEO_LOAI_TOA PRIMARY KEY (MaGiaToa),
    CONSTRAINT CK_GIA_THEO_LOAI_TOA_Loai CHECK (LoaiToa IN (N'Ghế', N'Giường')),
    CONSTRAINT CK_GIA_THEO_LOAI_TOA_Gia CHECK (GiaTien >= 0)
);

-- 10. Bảng GIA_THEO_TANG
CREATE TABLE GIA_THEO_TANG (
    MaGiaTang VARCHAR(10) NOT NULL,
    SoTang INT NOT NULL,
    GiaTien DECIMAL(18, 0),
    CONSTRAINT PK_GIA_THEO_TANG PRIMARY KEY (MaGiaTang),
    CONSTRAINT CK_GIA_THEO_TANG_SoTang CHECK (SoTang > 0),
    CONSTRAINT CK_GIA_THEO_TANG_Gia CHECK (GiaTien >= 0)
);

-- ================================================================
-- CẤP ĐỘ 3: CÁC BẢNG PHỤ THUỘC CẤP 1 (Có FK)
-- ================================================================

-- 11. Bảng TOA_TAU
CREATE TABLE TOA_TAU (
    MaToaTau VARCHAR(10) NOT NULL,
    MaDoanTau VARCHAR(10) NOT NULL,
    STT INT NOT NULL,
    LoaiToa NVARCHAR(10) NOT NULL,
    SLViTri INT,
    CONSTRAINT PK_TOA_TAU PRIMARY KEY (MaToaTau),
    CONSTRAINT CK_TOA_TAU_LoaiToa CHECK (LoaiToa IN (N'Ghế', N'Giường')),
    CONSTRAINT FK_TOA_TAU_DOAN_TAU FOREIGN KEY (MaDoanTau) REFERENCES DOAN_TAU(MaDoanTau)
);

-- 12. Bảng DANH_SACH_GA
CREATE TABLE DANH_SACH_GA (
    MaTuyenTau VARCHAR(10) NOT NULL,
    MaGaTau VARCHAR(10) NOT NULL,
    ThuTu INT,
    KhoangCach FLOAT,
    CONSTRAINT PK_DANH_SACH_GA PRIMARY KEY (MaTuyenTau, MaGaTau),
    CONSTRAINT FK_DANH_SACH_GA_TUYEN_TAU FOREIGN KEY (MaTuyenTau) REFERENCES TUYEN_TAU(MaTuyenTau),
    CONSTRAINT FK_DANH_SACH_GA_GA_TAU FOREIGN KEY (MaGaTau) REFERENCES GA_TAU(MaGaTau)
);

-- 13. Bảng CHUYEN_TAU
CREATE TABLE CHUYEN_TAU (
    MaChuyenTau VARCHAR(10) NOT NULL,
    MaTuyenTau VARCHAR(10),
    MaDoanTau VARCHAR(10),
    GaXuatPhat VARCHAR(10),
    GaKetThuc VARCHAR(10),
    TrangThai NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_CHUYEN_TAU PRIMARY KEY (MaChuyenTau),
    CONSTRAINT CK_CHUYEN_TAU_TrangThai CHECK (TrangThai IN (N'Chuẩn bị', N'Đang chạy', N'Hoàn thành', N'Hủy')),
    CONSTRAINT FK_CHUYEN_TAU_TUYEN_TAU FOREIGN KEY (MaTuyenTau) REFERENCES TUYEN_TAU(MaTuyenTau),
    CONSTRAINT FK_CHUYEN_TAU_DOAN_TAU FOREIGN KEY (MaDoanTau) REFERENCES DOAN_TAU(MaDoanTau),
    CONSTRAINT FK_CHUYEN_TAU_GaXuatPhat FOREIGN KEY (GaXuatPhat) REFERENCES GA_TAU(MaGaTau),
    CONSTRAINT FK_CHUYEN_TAU_GaKetThuc FOREIGN KEY (GaKetThuc) REFERENCES GA_TAU(MaGaTau)
);

-- 14. Bảng TAI_KHOAN
CREATE TABLE TAI_KHOAN (
    Email VARCHAR(255) NOT NULL,
    MaKH VARCHAR(10),
    MaNV VARCHAR(10),
    TenTaiKhoan VARCHAR(50),
    MatKhau VARCHAR(50) NOT NULL,
    TrangThai BIT NOT NULL,
    VaiTro NVARCHAR(20),
    CONSTRAINT PK_TAI_KHOAN PRIMARY KEY (Email),
    CONSTRAINT UQ_TAI_KHOAN_TenTaiKhoan UNIQUE (TenTaiKhoan),
    CONSTRAINT CK_TAI_KHOAN_VaiTro CHECK (VaiTro IN (N'Khách hàng', N'Nhân viên', N'Quản lý', N'Bán vé')),
    CONSTRAINT FK_TAI_KHOAN_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKhachHang),
    CONSTRAINT FK_TAI_KHOAN_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

-- 15. Bảng PHAN_CONG_BAN_VE
CREATE TABLE PHAN_CONG_BAN_VE (
    MaNV VARCHAR(10) NOT NULL,
    MaGa VARCHAR(10) NOT NULL,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME,
    CONSTRAINT PK_PHAN_CONG_BAN_VE PRIMARY KEY (MaNV, MaGa, NgayBatDau),
    CONSTRAINT CK_PHAN_CONG_BAN_VE_ThoiGian CHECK (NgayKetThuc IS NULL OR NgayBatDau < NgayKetThuc),
    CONSTRAINT FK_PHAN_CONG_BAN_VE_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_PHAN_CONG_BAN_VE_GA_TAU FOREIGN KEY (MaGa) REFERENCES GA_TAU(MaGaTau)
);

-- 16. Bảng BANG_LUONG
CREATE TABLE BANG_LUONG (
    MaBangLuong VARCHAR(10) NOT NULL,
    NgayNhanLuong DATETIME NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    LuongChinh DECIMAL(18, 0) NOT NULL,
    PhuCap DECIMAL(18, 0),
    TienPhat DECIMAL(18, 0),
    ThuLaoChuyenTau DECIMAL(18, 0),
    ThuLaoThayCa DECIMAL(18, 0),
    TongLuong DECIMAL(18, 0),
    CONSTRAINT PK_BANG_LUONG PRIMARY KEY (MaBangLuong),
    CONSTRAINT FK_BANG_LUONG_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

-- ================================================================
-- CẤP ĐỘ 4: CÁC BẢNG CHI TIẾT (Phụ thuộc vào Cấp độ 3)
-- ================================================================

-- 17. Bảng VI_TRI_TREN_TOA
CREATE TABLE VI_TRI_TREN_TOA (
    MaViTri VARCHAR(10) NOT NULL,
    MaToaTau VARCHAR(10) NOT NULL,
    STT INT,
    LoaiVT NVARCHAR(10) NOT NULL,
    CONSTRAINT PK_VI_TRI_TREN_TOA PRIMARY KEY (MaViTri),
    CONSTRAINT CK_VI_TRI_TREN_TOA_LoaiVT CHECK (LoaiVT IN (N'Ghế', N'Giường')),
    CONSTRAINT FK_VI_TRI_TOA_TAU FOREIGN KEY (MaToaTau) REFERENCES TOA_TAU(MaToaTau)
);

-- 18. Bảng THOI_GIAN_CHUYEN_TAU
CREATE TABLE THOI_GIAN_CHUYEN_TAU (
    MaChuyenTau VARCHAR(10) NOT NULL,
    MaGaTau VARCHAR(10) NOT NULL,
    DuKienXuatPhat DATETIME NOT NULL,
    DuKienDen DATETIME NOT NULL,
    ThucTeXuatPhat DATETIME,
    ThucTeDen DATETIME,
    CONSTRAINT PK_THOI_GIAN_CHUYEN_TAU PRIMARY KEY (MaChuyenTau, MaGaTau),
    CONSTRAINT FK_THOI_GIAN_CHUYEN_TAU FOREIGN KEY (MaChuyenTau) REFERENCES CHUYEN_TAU(MaChuyenTau),
    CONSTRAINT FK_THOI_GIAN_GA_TAU FOREIGN KEY (MaGaTau) REFERENCES GA_TAU(MaGaTau)
);

-- 19. Bảng PHAN_CONG_CHUYEN_TAU
CREATE TABLE PHAN_CONG_CHUYEN_TAU (
    MaPhanCong VARCHAR(10) NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    VaiTro NVARCHAR(30) NOT NULL,
    MaChuyenTau VARCHAR(10) NOT NULL,
    MaToa VARCHAR(10),
    TrangThai NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_PHAN_CONG_CHUYEN_TAU PRIMARY KEY (MaPhanCong),
    CONSTRAINT CK_PHAN_CONG_VaiTro CHECK (VaiTro IN (N'Nhân viên phụ trách lái', N'Nhân viên trưởng', N'Nhân viên phụ trách toa')),
    CONSTRAINT CK_PHAN_CONG_TrangThai CHECK (TrangThai IN (N'Nhận việc', N'Nghỉ', N'Đang làm', N'Xong')),
    CONSTRAINT FK_PHAN_CONG_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_PHAN_CONG_CHUYEN_TAU FOREIGN KEY (MaChuyenTau) REFERENCES CHUYEN_TAU(MaChuyenTau),
    CONSTRAINT FK_PHAN_CONG_TOA_TAU FOREIGN KEY (MaToa) REFERENCES TOA_TAU(MaToaTau)
);

-- 20. Bảng DAT_VE
CREATE TABLE DAT_VE (
    MaDatVe VARCHAR(10) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    MaChuyenTau VARCHAR(10) NOT NULL,
    ThoiGianDat DATETIME NOT NULL,
    HanThanhToan DATETIME NOT NULL,
    TongTienDuKien DECIMAL(18, 0),
    KenhDat NVARCHAR(20),
    TrangThai NVARCHAR(20),
    CONSTRAINT PK_DAT_VE PRIMARY KEY (MaDatVe),
    CONSTRAINT CK_DAT_VE_KenhDat CHECK (KenhDat IN (N'Online', N'Tại quầy')),
    CONSTRAINT CK_DAT_VE_TrangThai CHECK (TrangThai IN (N'Đang chờ', N'Đã thanh toán', N'Hủy')),
    CONSTRAINT FK_DAT_VE_TAI_KHOAN FOREIGN KEY (Email) REFERENCES TAI_KHOAN(Email),
    CONSTRAINT FK_DAT_VE_CHUYEN_TAU FOREIGN KEY (MaChuyenTau) REFERENCES CHUYEN_TAU(MaChuyenTau)
);

-- ================================================================
-- CẤP ĐỘ 5: CÁC BẢNG SÂU HƠN & GIAO DỊCH
-- ================================================================

-- 21. Bảng GIUONG
CREATE TABLE GIUONG (
    MaViTri VARCHAR(10) NOT NULL,
    Tang INT,
    Phong INT,
    CONSTRAINT PK_GIUONG PRIMARY KEY (MaViTri),
    CONSTRAINT FK_GIUONG_VI_TRI FOREIGN KEY (MaViTri) REFERENCES VI_TRI_TREN_TOA(MaViTri)
);

-- 22. Bảng DON_NGHI_PHEP
CREATE TABLE DON_NGHI_PHEP (
    MaDon VARCHAR(10) NOT NULL,
    MaPhanCong VARCHAR(10) NOT NULL, 
    NgayGui DATETIME NOT NULL,
    LyDo NVARCHAR(255),
    NVGuiDon VARCHAR(10) NOT NULL,
    NVDuyetDon VARCHAR(10),
    NVThayThe VARCHAR(10),
    TrangThai NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_DON_NGHI_PHEP PRIMARY KEY (MaDon),
    CONSTRAINT CK_DON_NGHI_PHEP_TrangThai CHECK (TrangThai IN (N'Đang chờ', N'Chấp nhận', N'Từ chối')),
    CONSTRAINT FK_DNP_NV_GuiDon FOREIGN KEY (NVGuiDon) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_DNP_NV_DuyetDon FOREIGN KEY (NVDuyetDon) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_DNP_NV_ThayThe FOREIGN KEY (NVThayThe) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_DNP_PhanCong FOREIGN KEY (MaPhanCong) REFERENCES PHAN_CONG_CHUYEN_TAU(MaPhanCong)
);

-- 23. Bảng VE_TAU
CREATE TABLE VE_TAU (
    MaVe VARCHAR(10) NOT NULL,
    MaKhachHang VARCHAR(10) NOT NULL,
    MaChuyenTau VARCHAR(10) NOT NULL,
    MaDatVe VARCHAR(10) NOT NULL,
    MaUuDai VARCHAR(10),
    ThoiGianXuatVe DATETIME,
    GaXuatPhat VARCHAR(10),
    GaDen VARCHAR(10),
    SoTienGiam DECIMAL(18, 0),
    GiaThuc DECIMAL(18, 0),
    TrangThai NVARCHAR(20) NOT NULL,
    MaViTri VARCHAR(10) NOT NULL,
    CONSTRAINT PK_VE_TAU PRIMARY KEY (MaVe),
    CONSTRAINT CK_VE_TAU_TrangThai CHECK (TrangThai IN (N'Giữ chỗ', N'Đã đặt', N'Đã dùng', N'Hủy vé', N'Đổi vé')),
    CONSTRAINT FK_VE_TAU_KHACH_HANG FOREIGN KEY (MaKhachHang) REFERENCES KHACH_HANG(MaKhachHang),
    CONSTRAINT FK_VE_TAU_CHUYEN_TAU FOREIGN KEY (MaChuyenTau) REFERENCES CHUYEN_TAU(MaChuyenTau),
    CONSTRAINT FK_VE_TAU_DAT_VE FOREIGN KEY (MaDatVe) REFERENCES DAT_VE(MaDatVe),
    CONSTRAINT FK_VE_TAU_UU_DAI FOREIGN KEY (MaUuDai) REFERENCES UU_DAI_GIA(MaUuDai),
    CONSTRAINT FK_VE_TAU_GaXuatPhat FOREIGN KEY (GaXuatPhat) REFERENCES GA_TAU(MaGaTau),
    CONSTRAINT FK_VE_TAU_GaDen FOREIGN KEY (GaDen) REFERENCES GA_TAU(MaGaTau),
    CONSTRAINT FK_VE_TAU_VI_TRI FOREIGN KEY (MaViTri) REFERENCES VI_TRI_TREN_TOA(MaViTri)
);

-- ================================================================
-- CẤP ĐỘ 6: BẢNG GIAO DỊCH CUỐI CÙNG
-- ================================================================

-- 24. Bảng DOI_VE
CREATE TABLE DOI_VE (
    MaDoiVe VARCHAR(10) NOT NULL,
    NVThucHien VARCHAR(10),
    MaVeCu VARCHAR(10) NOT NULL,
    MaVeMoi VARCHAR(10) NOT NULL,
    ThoiGianDoi DATETIME NOT NULL,
    PhiPhat DECIMAL(18, 0),
    TrangThai VARCHAR(20) NOT NULL,
    CONSTRAINT PK_DOI_VE PRIMARY KEY (MaDoiVe),
    CONSTRAINT CK_DOI_VE_TrangThai CHECK (TrangThai IN ('Đang chờ', 'Đã đổi', 'Hủy')),
    CONSTRAINT FK_DOI_VE_NHAN_VIEN FOREIGN KEY (NVThucHien) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_DOI_VE_VeCu FOREIGN KEY (MaVeCu) REFERENCES VE_TAU(MaVe),
    CONSTRAINT FK_DOI_VE_VeMoi FOREIGN KEY (MaVeMoi) REFERENCES VE_TAU(MaVe)
);

-- 25. Bảng HOA_DON
CREATE TABLE HOA_DON (
    MaHoaDon VARCHAR(10) NOT NULL,
    MaDatVe VARCHAR(10),
    MaDoiVe VARCHAR(10),
    MaNVLap VARCHAR(10),
    ThoiGianThanhToan DATETIME NOT NULL,
    HinhThucThanhToan NVARCHAR(20) NOT NULL,
    GiaTien DECIMAL(18, 0) NOT NULL,
    CONSTRAINT PK_HOA_DON PRIMARY KEY (MaHoaDon),
    CONSTRAINT CK_HOA_DON_HinhThuc CHECK (HinhThucThanhToan IN (N'Online', N'Tại quầy')),
    CONSTRAINT FK_HOA_DON_DAT_VE FOREIGN KEY (MaDatVe) REFERENCES DAT_VE(MaDatVe),
    CONSTRAINT FK_HOA_DON_DOI_VE FOREIGN KEY (MaDoiVe) REFERENCES DOI_VE(MaDoiVe),
    CONSTRAINT FK_HOA_DON_NHAN_VIEN FOREIGN KEY (MaNVLap) REFERENCES NHAN_VIEN(MaNV)
);
GO