import React, { useState, useEffect } from 'react';
import Modal from '../common/Modal'; // Keeping your custom Modal component
import '../../styles/pages/TrainManagementPage.css';

const AddTrainModal = ({ isOpen, isEdit, initialData, onClose, onSave }) => {
  // State matches your API Payload structure
  const [formData, setFormData] = useState({
    tenTau: '',
    hangSanXuat: '',
    ngayVanHanh: '',
    loaiTau: 'Hạng sang',
    trangThai: 'Hoạt động'
  });

  // Effect: Reset form or Fill data when modal opens
  useEffect(() => {
    if (isOpen) {
        if (isEdit && initialData) {
            // MAP Frontend Data -> API Format for the Form
            setFormData({
                tenTau: initialData.trainName || initialData.tenTau || '',
                hangSanXuat: initialData.company || initialData.hangSanXuat || '',
                
                // Format Date to YYYY-MM-DD for input[type="date"]
                ngayVanHanh: initialData.operationDate 
                  ? new Date(initialData.operationDate).toISOString().split('T')[0] 
                  : '',
                
                // Map VIP/Normal back to API values
                loaiTau: initialData.type === 'VIP' ? 'Hạng sang' : 'Bình thường',
                
                // Map active/maintenance back to API values
                trangThai: initialData.status === 'active' ? 'Hoạt động' : 'Bảo trì'
            });
        } else {
            // Reset form for Add New
            setFormData({
                tenTau: '',
                hangSanXuat: 'Đường sắt Việt Nam', // Default value
                ngayVanHanh: new Date().toISOString().split('T')[0], // Default to today
                loaiTau: 'Hạng sang',
                trangThai: 'Hoạt động'
            });
        }
    }
  }, [isOpen, isEdit, initialData]);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSave = () => {
    // Validation: Only name is strictly required usually, others have defaults
    if (!formData.tenTau) {
      alert("Vui lòng nhập Tên đoàn tàu!");
      return;
    }
    
    // Prepare object to save
    const dataToSave = {
        ...formData,
        // If editing, we need to pass the ID back so parent knows what to update
        // (The API doesn't need ID in body for create, but parent needs it for update URL)
        id: isEdit ? initialData.id : undefined 
    };
    
    onSave(dataToSave); 
  };

  const modalActions = (
    <>
      <button onClick={onClose} className="modal-btn-cancel">Hủy</button>
      <button onClick={handleSave} className="modal-btn-save">
        {isEdit ? 'Cập nhật' : 'Thêm mới'}
      </button>
    </>
  );

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={onClose} 
      title={isEdit ? "Cập nhật đoàn tàu" : "Thêm đoàn tàu mới"} 
      actions={modalActions}
    >
      <p className="form-description">
        {isEdit ? "Chỉnh sửa thông tin đoàn tàu" : "Nhập thông tin để tạo đoàn tàu mới"}
      </p>
      
      <div className="form-stack">
        {/* Removed ID Input (Auto-generated by API) */}
        
        {/* Tên đoàn tàu */}
        <div className="form-group">
          <label>Tên đoàn tàu <span className="text-red-500">*</span></label>
          <input 
            type="text" 
            name="tenTau" 
            value={formData.tenTau} 
            onChange={handleChange} 
            placeholder="VD: SE1 Thống Nhất" 
            className="form-input" 
          />
        </div>
        
        <div className="grid grid-cols-2 gap-4">
            {/* Hãng sản xuất */}
            <div className="form-group">
                <label>Hãng tàu</label>
                <input 
                  type="text" 
                  name="hangSanXuat" 
                  value={formData.hangSanXuat} 
                  onChange={handleChange} 
                  placeholder="VD: Gia Lam Railway"
                  className="form-input" 
                />
            </div>
            {/* Ngày vận hành */}
            <div className="form-group">
                <label>Ngày vận hành</label>
                <input 
                  type="date" 
                  name="ngayVanHanh" 
                  value={formData.ngayVanHanh} 
                  onChange={handleChange} 
                  className="form-input" 
                />
            </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
            {/* Loại tàu */}
            <div className="form-group">
                <label>Loại tàu</label>
                <select 
                  name="loaiTau" 
                  value={formData.loaiTau} 
                  onChange={handleChange} 
                  className="form-select"
                >
                    <option value="Hạng sang">Hạng sang (VIP)</option>
                    <option value="Bình thường">Bình thường</option>
                </select>
            </div>
            {/* Trạng thái */}
            <div className="form-group">
                <label>Trạng thái</label>
                <select 
                  name="trangThai" 
                  value={formData.trangThai} 
                  onChange={handleChange} 
                  className="form-select"
                >
                    <option value="Hoạt động">Hoạt động</option>
                    <option value="Bảo trì">Bảo trì</option>
                </select>
            </div>
        </div>
      </div>
    </Modal>
  );
};

export default AddTrainModal;